# Generated by Django 6.0.7 on 2026-08-04 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='annees_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidat',
            name='competences',
            field=models.TextField(blank=True, help_text='Liste de mots-clés ou compétences'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='disponibilite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='lettre_motivation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='notes_recruteur',
            field=models.TextField(blank=True, help_text='Notes internes (masquées au candidat)'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='pretention_salariale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='source_recrutement',
            field=models.CharField(choices=[('SITE_CARRIERE', 'Site Carrière'), ('LINKEDIN', 'LinkedIn'), ('RECOMMANDATION', 'Recommandation'), ('AUTRE', 'Autre')], default='SITE_CARRIERE', max_length=30),
        ),
        migrations.AddField(
            model_name='candidat',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidature',
            name='commentaire',
            field=models.TextField(blank=True, help_text="Notes d'évaluation spécifiques à cette candidature"),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_entretien',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='note_evaluation',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Note globale de 1 à 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='avantages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='date_limite_candidature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='departement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='mode_travail',
            field=models.CharField(choices=[('PRESENTIEL', 'Présentiel'), ('HYBRIDE', 'Hybride'), ('TELECOMMUTE', 'Télétravail')], default='PRESENTIEL', max_length=20),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='niveau_etudes_requis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='niveau_experience_requis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='nombre_postes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='salaire_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='salaire_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('FREELANCE', 'Freelance'), ('ALTERNANCE', 'Alternance')], default='CDI', max_length=20),
        ),
    ]
