# Generated by Django 6.0.7 on 2026-08-07 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0003_candidat_annees_experience_candidat_competences_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidature',
            old_name='date_entretien',
            new_name='date_entretien_rh',
        ),
        migrations.AddField(
            model_name='candidat',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_entretien_technique',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='numero_dossier',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='candidature',
            unique_together={('candidat', 'offre')},
        ),
    ]
