# Generated by Django 6.0.7 on 2026-08-14 11:15

import django.core.validators
import recrutement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0004_rename_date_entretien_candidature_date_entretien_rh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, validators=[recrutement.models.validate_date_naissance]),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir uniquement des chiffres, espaces, ou les symboles +, -, ().', regex='^\\+?[0-9\\s\\-()]{7,20}$')]),
        ),
    ]
