# Generated by Django 6.0.7 on 2026-08-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0005_alter_candidat_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offreemploi',
            name='competences_cles',
            field=models.TextField(blank=True, help_text='Entrez les compétences séparées par des virgules avec leur priorité. Ex: Python (Indispensable), Docker (Important), AWS (Souhaitable)'),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='horaires_travail',
            field=models.CharField(choices=[('PLEIN_TEMPS', 'Plein temps (35h-40h/semaine)'), ('TEMPS_PARTIEL', 'Temps partiel'), ('FLEXIBLE', 'Horaires flexibles / Résultats'), ('POSTE_3X8', 'Travail posté (3x8 / 2x8)')], default='PLEIN_TEMPS', max_length=30),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='langues_requises',
            field=models.CharField(blank=True, help_text='Ex: Français (Courant), Anglais (B2 / Technique)', max_length=255),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='niveau_hierarchique',
            field=models.CharField(choices=[('JUNIOR', 'Junior / Débutant'), ('CONFIRME', 'Confirmé / Intermédiaire'), ('SENIOR', 'Sénior / Expert'), ('LEAD', 'Team Lead / Manager'), ('DIRECTION', 'Direction / Cadre Dirigeant')], default='CONFIRME', max_length=30),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='outils_technologies',
            field=models.CharField(blank=True, help_text='Ex: Git, Jira, PostgreSQL, VS Code', max_length=255),
        ),
    ]
