# Generated by Django 6.0.7 on 2026-08-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0006_offreemploi_competences_cles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
