# Generated by Django 6.0.7 on 2026-07-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('candidat', 'Candidat'), ('recruteur', 'Recruteur'), ('admin', 'Administrateur')], default='admin', max_length=20),
        ),
    ]
