# Generated by Django 6.0.7 on 2026-08-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse_entreprise',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='site_web',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
