# Generated by Django 6.0.7 on 2026-07-27 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('competences', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key='True', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('description_entreprise', models.TextField(blank=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
